FROM ampregistry:5000/node_taobao:10.7.0

MAINTAINER huanganwu<huanganwu@megvii.com>

WORKDIR /opt/project

ADD djx_railway /opt/project/djx_railway

WORKDIR /opt/project/djx_railway

CMD ["npm","run","server"]
